FROM node:lts-alpine as build

WORKDIR /client

COPY package.json ./

RUN npm i

COPY . .

RUN npm run build


FROM nginx as production

RUN mkdir /client

COPY --from=build /client/dist /client

COPY nginx.conf /etc/nginx/nginx.conf